networks:
  app-net:
    driver: bridge

services:
  stats-server:
    build:
      context: ./stats/stats-svc
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    networks:
      - app-net

  stats-db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8462
    ports:
      - "5432:5432"
    networks:
      - app-net

  ewm-service:
    build:
      context: ./ewm-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      DB_HOST: ewm-db
      DB_NAME: ewm
      DB_USER: postgres
      DB_PASSWORD: 8462
    networks:
      - app-net

  ewm-db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: ewm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8462
    ports:
      - "5433:5432"
    networks:
      - app-net
