services:
  stats-server:
    build:
      context: ./stats/stats-svc
      dockerfile: Dockerfile
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:16.1

  ewm-service:
    build:
      context: ./ewm-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:16.1
